// Generated by https://quicktype.io

export interface PokemonGql {
    pokemon_v2_pokemonspecies: PokemonGqlPokemonV2Pokemonspecy[];
}

export interface PokemonGqlPokemonV2Pokemonspecy {
    __typename:                string;
    pokemon_v2_evolutionchain: PokemonV2Evolutionchain;
}

export interface PokemonV2Evolutionchain {
    __typename:                string;
    pokemon_v2_pokemonspecies: PokemonV2EvolutionchainPokemonV2Pokemonspecy[];
}

export interface PokemonV2EvolutionchainPokemonV2Pokemonspecy {
    __typename:                           string;
    pokemon_v2_pokemons:                  PokemonV2PokemonElement[];
    pokemon_v2_pokemonspeciesflavortexts: PokemonV2Pokemonspeciesflavortext[];
    pokemon_v2_pokemonspeciesnames:       PokemonV2[];
}

export interface PokemonV2PokemonElement {
    __typename:                  PokemonV2PokemonTypename;
    name:                        string;
    height:                      number;
    weight:                      number;
    pokemon_v2_pokemonforms:     PokemonV2Pokemonform[];
    is_default:                  boolean;
    id:                          number;
    pokemon_v2_pokemonabilities: PokemonV2Pokemonability[];
}

export enum PokemonV2PokemonTypename {
    PokemonV2Pokemon = "pokemon_v2_pokemon",
}

export interface PokemonV2Pokemonability {
    __typename:         PokemonV2PokemonabilityTypename;
    is_hidden:          boolean;
    pokemon_v2_ability: PokemonV2;
}

export enum PokemonV2PokemonabilityTypename {
    PokemonV2Pokemonability = "pokemon_v2_pokemonability",
}

export interface PokemonV2 {
    __typename: PokemonV2PokemonspeciesnameTypename;
    name:       string;
}

export enum PokemonV2PokemonspeciesnameTypename {
    PokemonV2Ability = "pokemon_v2_ability",
    PokemonV2Pokemonformname = "pokemon_v2_pokemonformname",
    PokemonV2Pokemonspeciesname = "pokemon_v2_pokemonspeciesname",
    PokemonV2Stat = "pokemon_v2_stat",
    PokemonV2Type = "pokemon_v2_type",
    PokemonV2Version = "pokemon_v2_version",
}

export interface PokemonV2Pokemonform {
    __typename:                  PokemonV2PokemonformTypename;
    name:                        string;
    form_name:                   string;
    pokemon_v2_pokemonformnames: PokemonV2[];
    pokemon_v2_pokemon:          PokemonV2PokemonformPokemonV2Pokemon;
}

export enum PokemonV2PokemonformTypename {
    PokemonV2Pokemonform = "pokemon_v2_pokemonform",
}

export interface PokemonV2PokemonformPokemonV2Pokemon {
    __typename:              PokemonV2PokemonTypename;
    pokemon_v2_pokemonstats: PokemonV2Pokemonstat[];
    pokemon_v2_pokemontypes: PokemonV2Pokemontype[];
}

export interface PokemonV2Pokemonstat {
    __typename:      PokemonV2PokemonstatTypename;
    pokemon_v2_stat: PokemonV2;
    base_stat:       number;
}

export enum PokemonV2PokemonstatTypename {
    PokemonV2Pokemonstat = "pokemon_v2_pokemonstat",
}

export interface PokemonV2Pokemontype {
    __typename:      PokemonV2PokemontypeTypename;
    slot:            number;
    pokemon_v2_type: PokemonV2;
}

export enum PokemonV2PokemontypeTypename {
    PokemonV2Pokemontype = "pokemon_v2_pokemontype",
}

export interface PokemonV2Pokemonspeciesflavortext {
    __typename:         PokemonV2PokemonspeciesflavortextTypename;
    flavor_text:        string;
    pokemon_v2_version: PokemonV2;
}

export enum PokemonV2PokemonspeciesflavortextTypename {
    PokemonV2Pokemonspeciesflavortext = "pokemon_v2_pokemonspeciesflavortext",
}
